Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "master" do |master|
    master.vm.network "private_network", type: "dhcp", auto_config: false
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end

  # Node 01
  config.vm.define "node01" do |node01|
    node01.vm.network "private_network", ip: "192.168.50.11"
    node01.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end

  # Node 02
  config.vm.define "node02" do |node02|
    node02.vm.network "private_network", ip: "192.168.50.12"
    node02.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end

  # Node 03
  config.vm.define "node03" do |node03|
    node03.vm.network "private_network", ip: "192.168.50.13"
    node03.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io
      sudo systemctl enable docker
      sudo systemctl start docker
    SHELL
  end
end
